services:
  postgres:
    image: postgres:15-alpine
    container_name: hm_database
    environment:
      POSTGRES_DB: hm_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123456
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5436:5432"
    networks:
      - hm_network

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: hm_mosquitto
    ports:
      - "1883:1883"
    environment:
      MOSQUITTO_USERNAME: admin
      MOSQUITTO_PASSWORD: admin123456
    command: >
      sh -c "
      mosquitto_passwd -c -b /mosquitto/config/passwd.txt $${MOSQUITTO_USERNAME} $${MOSQUITTO_PASSWORD} &&
      mosquitto -c /mosquitto-no-auth.conf
      "
    networks:
      - hm_network

networks:
  hm_network:
    driver: bridge
